/*
 * EEPROM_SPI_PdC.h
 *
 *  Created on: 11 oct. 2021
 *      Author: Pablo Jesús Carrizo
 */

#ifndef PRACTICAS_PROGRAMACION_PRACTICAS_PROTOCOL_COM_PDC_TPF_1_INC_EEPROM_SPI_PDC_H_
#define PRACTICAS_PROGRAMACION_PRACTICAS_PROTOCOL_COM_PDC_TPF_1_INC_EEPROM_SPI_PDC_H_


int main( void );
//void spi_Config_EEPROM25LC1024( spiMap_t spi );
//float write_data_EEPROM25LC1024 (void);
#endif /* PRACTICAS_PROGRAMACION_PRACTICAS_PROTOCOL_COM_PDC_TPF_1_INC_EEPROM_SPI_PDC_H_ */
